name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: vcpkg
        with: { committish: "0e47c1985273129e4d0ee52ff73bed9125555de8" }

      - run: |
          printf $'Cache hit: \'%s\'\nVCPKG_DEFAULT_BINARY_CACHE: \'%s\'\n' \
            "${{ steps.vcpkg.outputs.cache-hit }}" \
            "$VCPKG_DEFAULT_BINARY_CACHE"
          $VCPKG_ROOT/vcpkg version
