name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: vcpkg
        with:
          committish: "96b5ced82828ecaf67e6010a892c98d3e96ed1c2"
          cache-version: default

      - run: |
          printf $'Cache hit: \'%s\'\nVCPKG_DEFAULT_BINARY_CACHE: \'%s\'\n' \
            "${{ steps.vcpkg.outputs.cache-hit }}" \
            "$VCPKG_DEFAULT_BINARY_CACHE"
          $VCPKG_ROOT/vcpkg version
